# -*- coding: utf-8 -*-
"""conversor de moeda.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vZWUyC-q76Mb0Qv34IHcBEvLlI9fQnLm
"""

from time import sleep
for c in range(0,4):# 
        print(c)
        sleep(1)
print('Bem vindo ao conversor de moedas:')
comecar = True
while comecar == True :
    continuar = input('Digite enter se quiser iniciar/continuar: e digite X para sair').upper()# deixar a letra maiscula
    for c in range(0,4):
        print(c)# 
        sleep(1)#serve para da um time de um numero pro outro
    if continuar == '':
        pass # passar 
        moeda = str(input('''Em qual moeda você deseja converter:
         Dodoalar - Digite DOLAR
        Euro - Digite EURO
        ''')).upper()
        if moeda == 'DOLAR':
                valor = float(input('Qual o valor em R$ :'))
                conversao = valor * 0.19
                print(f'O valor é em dolar é {conversao}')
        elif moeda == 'EURO':
                valor = float(input('Qual valor em R$ :'))
                conversao = valor * 0.18
                print(f'O valor é em euro é {conversao}')
        else:
            break  # parar o programa         
    else:
        break # parar o programa apos eu aperta o x